name: flame_test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: ^3.7.2
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  animate_do: ^4.2.0
  flame: ^1.27.0
  flame_audio: ^2.11.3
  flutter_stepper: ^0.0.1
  audioplayers: ^6.4.0
  flutter_svg: ^2.1.0
  chat_bubbles: ^1.7.0
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  audio_waveforms: ^1.3.0
  flutter_custom_clippers: ^2.1.0
  # flutter_sound: ^9.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed:
  build_runner: ^2.4.13
  # json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
